### ISSUE TITLE
To add PULL_REQUEST_TEMPLATES

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/getbuttons.io#11]
Need to add a pull request template as well. This will save the time of the contributors, as well as the project maintainers'. 

There will be a short description asking questions related to the code changes done and some checklists as well :)

Refer to this link to get a proper idea - https://github.com/stevemao/github-issue-templates

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign this to me under LGM SOC.

**Comment by yashsehgal** [comment]
> I would like to work on this issue. Kindly assign this to me under LGM SOC.

Thanks for reaching out, you can get started. Also, your contributions under LGMSoc will be considered only after 10. Keep that in mind.

**Comment by SamikshaSankar** [comment]
I would like to contribute on this issue

**Comment by yashsehgal** [comment]
Sure, I am assigning this issue to you both. Good luck 🚀

**Comment by yashsehgal** [comment]
Sorry for the inconvenience @SamikshaSankar 
Actually, according to the rules I first need to assign this issue to @akshatvirmani 

But surely, you can work on other issues as well. 

Sorry once again :D

**Comment by SamikshaSankar** [comment]
Yeah .. totally agreed
