### ISSUE TITLE
Logo needed for GetButtons.io

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/getbuttons.io#15]
**Here are some green squares for all the designers out there -** We need a logo for getbuttons.io that will be used everywhere such as branding, website, project display image, docs, and in general wherever we'll show getbuttons.io project.

**Things we are mainly looking for in the logo**
- The logo should be saying the type of project this is.
- We usually use text-based logos (1-2 alphabets are fine as well)
- Don't use generic designs
- Other than these points, we need your open innovation, feel free to design whatever you have in your mind.

We are eagerly waiting for your designs 🚀

**Comment by mayankmohak** [comment]
can I get this issue.

**Comment by yashsehgal** [comment]
Hey @mayankmohak 👋🏽 You can get started with this issue.

**Comment by Astitva7717** [comment]
Can I try this one too??

**Comment by mayankmohak** [comment]
sure @yashsehgal  I would love to make the one.

**Comment by yashsehgal** [comment]
Hey 👋🏽 @Astitva7717 
I would love to assign this to you, but it's already assigned to @mayankmohak 
You can try working on any other issue as of now 😃

**Comment by mayankmohak** [comment]
i have made a logo is it good to go @yashsehgal 
![logo](https://user-images.githubusercontent.com/63801800/121647151-b33ce000-cab3-11eb-9c24-214f9f38cbc5.png)

**Comment by yashsehgal** [comment]
Well @mayankmohak 
This is not that interesting, You can try making some more designs.

Refer to the logos mentioned below (Just to get an idea)
![image](https://user-images.githubusercontent.com/62352288/121652129-f483be80-cab8-11eb-8bec-4d3cb547e5f0.png)
![image](https://user-images.githubusercontent.com/62352288/121652185-049b9e00-cab9-11eb-9d07-3501662d6476.png)
![image](https://user-images.githubusercontent.com/62352288/121652231-10876000-cab9-11eb-9613-198c34ac0d5e.png)
![image](https://user-images.githubusercontent.com/62352288/121652274-1aa95e80-cab9-11eb-813b-bd31192924c4.png)

**Comment by mayankmohak** [comment]
you  can assign @Astitva7717

**Comment by yashsehgal** [comment]
No issues @mayankmohak 👍🏽 It's great that you have shown your efforts 🚀

**Comment by yashsehgal** [comment]
Go for it @Astitva7717 The issue has been assigned to you 👍🏽

**Comment by ayushsoni1010** [comment]
I want to work on this issue 
Kindly assign it to me  :)

**Comment by yashsehgal** [comment]
Sure, I can assign this issue to you @ayushsoni1010 
Before that, what's the status right now @Astitva7717??

**Comment by varunwho** [comment]
Can I work on this?

**Comment by varunwho** [comment]
Hey I've come up with this design
![GetButtons](https://user-images.githubusercontent.com/53107832/122002102-f1494500-cdce-11eb-83e6-237ca6832bb9.png)
