### ISSUE TITLE
Broken links in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by mayankmohak** [DesignSystemsOSS/getbuttons.io#19]
**Describe the bug**
Links in contributing docs if broken [link](https://github.com/DesignSystemsOSS/getbuttons.io/blob/master/CONTRIBUTING.md#step-01-fork-this-project)

**Expected behavior**
Broken links to be restored. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63801800/121459829-93c98880-c9c9-11eb-8bf3-796417839814.png)

Please assign me under LGM-SOC 2021

**Comment by yashsehgal** [comment]
Hey @mayankmohak 👋🏽 
Thanks for raising this issue. Sure, I can assign you this issue ✅

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21
