### ISSUE TITLE
Adding contributors in README.md

### ISSUE THREAD

**Issue by shriya030** [DesignSystemsOSS/getbuttons.io#21]
Please assign me this issue as a part of LGMSOC.

**Comment by yashsehgal** [comment]
Sure @shriya030 👍🏽 You can start working on this issue.

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by yashsehgal** [comment]
Hey, @jayant766 👋🏽 Glad to see your interest in this issue, But this task is already assigned to @shriya030 
If they want to pass it over in the future, I will assign this issue to you :D

Have a great day 🚀

**Comment by shriya030** [comment]
Hey @yashsehgal, new labels are out. Please update current ones to the new ones.

**Comment by yashsehgal** [comment]
Sure @shriya030 👍🏽 Thanks for reminding me!
