### ISSUE TITLE
Re-implementation of Primary Buttons

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/getbuttons.io#26]
## Are you a part of LGM SOC' 21 ❔
- [x] Yes ✅
- [ ] No  ❎

**Describe the bug**
- Some new designs to be implemented in Primary Button components

**To Reproduce**
- Steps to reproduce the behavior:
1. Follow the screenshot given below, in order to implement the buttons
![image](https://user-images.githubusercontent.com/62352288/121540046-c6a06a80-ca23-11eb-991f-a9ac3916a219.png)
2. Implement this feature in both CSS and JXS-CSS modules

**Comment by WebShivam** [comment]
Hi Yash! I think I can fix this issue. I'd appreciate if you could assign me, so I can start working on it
Thank you!
