### ISSUE TITLE
Fade on hover button

### ISSUE THREAD

**Issue by akshatvirmani** [DesignSystemsOSS/getbuttons.io#39]
- Paste the screenshot or link of your design 📷
Before clicking
![image](https://user-images.githubusercontent.com/77536248/122217539-220ea480-cecb-11eb-9cdd-aac69361e019.png)
After clicking
![image](https://user-images.githubusercontent.com/77536248/122217645-38b4fb80-cecb-11eb-8493-ecc3cd62f22b.png)

- Is your design request related to an issue❓
No

- Add any additional information that you want us to know (optional) 📋
Before clicking the button the color is light and after clicking it gets brighter in color.

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign this to me.

**Comment by yashsehgal** [comment]
Yes, You can get started with this issue @akshatvirmani 👍🏽 
- First, you need to create a PR with CSS Implementation
- After, you can simply contribute by adding react code as well.

Feel free to ask your queries :D

**Comment by akshatvirmani** [comment]
okay
