### ISSUE TITLE
Add Program Section in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [DesignSystemsOSS/getbuttons.io#41]
## Are you a part of LGM SOC' 21 ❔
- [x] Yes ✅
- [ ] No  ❎

Add program section to represent that this project is a part of LGM-SOC'21.

**Comment by ishitakapoor26** [comment]
@yashsehgal pls assign me this issue.

**Comment by kanak22** [comment]
@ishitakapoor26 firstly finish your other issues then we will assign it to u :)

**Comment by padmajabhol** [comment]
Interested. Can you assign this to me?

**Comment by Diksha02** [comment]
please assign me this issue under LGMSOC'21

**Comment by kanak22** [comment]
sure, Go Ahead @Diksha02  :)

**Comment by ishitakapoor26** [comment]
@kanak i asked first.

**Comment by kanak22** [comment]
@ishitakapoor26 u didnt updated us on whether u completed all of your previous assigned issues or not ...no worries u still have the other issue that is based on readme....kindly complete that :)
