### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [DesignSystemsOSS/getbuttons.io#42]
## Are you a part of LGM SOC' 21 ❔
- [x] Yes ✅
- [ ] No  ❎

Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@yashsehgal pls assign me this issue.

**Comment by ishitakapoor26** [comment]
Like this 
![Uploading score card.PNG…]()

**Comment by ishitakapoor26** [comment]
Like this 
![score card](https://user-images.githubusercontent.com/78542333/122352787-0eb41580-cf6d-11eb-946c-512fb2b6b66c.PNG)

**Comment by kanak22** [comment]
Here you go :)

**Comment by kanak22** [comment]
@ishitakapoor26 are you working on it ?

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 are you working on it ?

Yeah!
