### ISSUE TITLE
Adding Color change on hover button

### ISSUE THREAD

**Issue by akshatvirmani** [DesignSystemsOSS/getbuttons.io#45]
- Paste the screenshot or link of your design 📷
before
![blue](https://user-images.githubusercontent.com/77536248/122643048-1e795880-d12b-11eb-9ba8-fbc24670bfbf.PNG)
after
![b2](https://user-images.githubusercontent.com/77536248/122643056-2802c080-d12b-11eb-8bb2-1ebb476b74e2.PNG)

- Is your design request related to an issue❓
No

- Add any additional information that you want us to know (optional) 📋
Hovering over the button makes it change color.

**Comment by varshitha1707** [comment]
I would like to work on this issue, Please assign it to me under LGMSOC21

**Comment by yashsehgal** [comment]
Hey, @varshitha1707 👋🏽 Glad to see your interest in this project. Actually, we discussed closing this issue. You may look into other open issues or create one if you have any suggestions to be made.
