### ISSUE TITLE
add more badges and move them to the top

### ISSUE THREAD

**Issue by Umesh-01** [DesignSystemsOSS/getbuttons.io#46]
## Are you a part of LGM SOC' 21 ❔
- [x] Yes ✅
- [ ] No  ❎

## Is your feature request related to a problem? Please describe.
Move badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc. 

![image](https://user-images.githubusercontent.com/83420185/122651079-27325480-d154-11eb-8ae8-f20702478b27.png)

## Describe the solution you'd like to add.
I will add some more badges and also will move them to the top so that the README.md file will look more interactive and awesome.

**Comment by Umesh-01** [comment]
@yashsehgal @atharvagadkari05 should I work on this??

**Comment by yashsehgal** [comment]
what badges you're planning to add? @Umesh-01

**Comment by Umesh-01** [comment]
@yashsehgal I will add badges for forks, contributors, PRs (open, closed), watcher, etc..
and may be some general badges like open source, built by Developers, etc.

**Comment by Umesh-01** [comment]
@yashsehgal should I make these changes??

**Comment by yashsehgal** [comment]
Alright @Umesh-01 You can get started 👍🏽
