### ISSUE TITLE
To add ISSUE_TEMPLATES

### ISSUE THREAD

**Issue by yashsehgal** [DesignSystemsOSS/getbuttons.io#9]
We need to add 3 issue templates in this project to make it easy for the users to raise more issues with relevant descriptions and labels.

Issue templates to be added
- Bug Report
- Feature Request
- Design Implementation Request

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign this to me under LGM SOC.

**Comment by yashsehgal** [comment]
Sure @akshatvirmani 👍🏽 Go ahead :)

**Comment by yashsehgal** [comment]
Also, your contributions under LGMSoc will be considered only after 10. Keep that in mind. 😃

**Comment by RiyaGupta89** [comment]
May I also work under this project?
